# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-20 08:41
from __future__ import unicode_literals

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_id', models.IntegerField(verbose_name=assets.models.Manufacturer)),
                ('part_number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_implemented', models.DateField(blank=True, null=True)),
                ('maint_notes', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Organization',
                'managed': False,
            },
        ),
    ]
